spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/quartierfest
spring.datasource.username=qfuser
spring.datasource.password=qfpass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true