-- DB-001: Flyway-Baseline — Ist-Stand des von Hibernate (ddl-auto=update) erzeugten Schemas,
-- eingefroren am 2026-09-08 (pg_dump der Dev-DB, bereinigt; lesbare Constraint-Namen statt Hibernate-Hashes).
--
-- Bestehende DBs (Prod, lokale Dev-DB) werden via spring.flyway.baseline-on-migrate=true auf V1
-- baselined — dieses Skript läuft dort NICHT. Es baut nur leere DBs (CI, neue Dev-DBs) auf.
-- Jede künftige Entity-Änderung bekommt ein neues V<n>__*.sql im selben PR; ddl-auto=validate
-- prüft beim Start, dass Entities und Schema zusammenpassen.

-- ---------------------------------------------------------------------------
-- Stammdaten
-- ---------------------------------------------------------------------------

CREATE TABLE person (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vorname         varchar(255) NOT NULL,
    name            varchar(255) NOT NULL,
    telefonnummer   varchar(255),
    mobilenummer    varchar(255),
    email           varchar(255),
    partei_id       bigint
);

CREATE TABLE partei (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bezeichnung         varchar(255) NOT NULL,
    adresse             varchar(255) NOT NULL,
    twint_aktiv         boolean NOT NULL,
    twint_mobilenummer  varchar(255)
);

ALTER TABLE person ADD CONSTRAINT fk_person_partei FOREIGN KEY (partei_id) REFERENCES partei (id);

CREATE TABLE event (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datum                  date NOT NULL,
    startzeit              time(0) NOT NULL,
    standort               varchar(255) NOT NULL,
    alternativer_standort  varchar(255),
    zeit_aufstellen        time(0),
    zeit_aufraumen         time(0)
);

-- ---------------------------------------------------------------------------
-- Planung
-- ---------------------------------------------------------------------------

CREATE TABLE einladung (
    id                           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id                     bigint NOT NULL,
    partei_id                    bigint NOT NULL,
    status                       varchar(255) NOT NULL,
    anzahl_personen              integer,
    hilft_aufstellen             boolean,
    hilft_aufraumen              boolean,
    buffet_beitrag               varchar(255),
    buffet_beitrag_beschreibung  varchar(255),
    bestaetigung_versendet       boolean NOT NULL,
    CONSTRAINT fk_einladung_event  FOREIGN KEY (event_id)  REFERENCES event (id),
    CONSTRAINT fk_einladung_partei FOREIGN KEY (partei_id) REFERENCES partei (id),
    CONSTRAINT einladung_status_check        CHECK (status IN ('OFFEN', 'ANGEMELDET', 'ABGEMELDET')),
    CONSTRAINT einladung_buffet_beitrag_check CHECK (buffet_beitrag IN ('KEINER', 'SALAT', 'BROT_ZOPF', 'DESSERT', 'WEITERE'))
);

CREATE TABLE teilnahme (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    einladung_id              bigint NOT NULL,
    anzahl_personen_effektiv  integer,
    hilft_aufstellen          boolean,
    hilft_aufraumen           boolean,
    CONSTRAINT fk_teilnahme_einladung FOREIGN KEY (einladung_id) REFERENCES einladung (id),
    CONSTRAINT uk_teilnahme_einladung UNIQUE (einladung_id)
);

CREATE TABLE teilnahme_buffet_beitrag (
    teilnahme_id  bigint NOT NULL,
    art           varchar(255),
    beschreibung  varchar(255),
    CONSTRAINT fk_teilnahme_buffet_beitrag_teilnahme FOREIGN KEY (teilnahme_id) REFERENCES teilnahme (id),
    CONSTRAINT teilnahme_buffet_beitrag_art_check CHECK (art IN ('KEINER', 'SALAT', 'BROT_ZOPF', 'DESSERT', 'WEITERE'))
);

CREATE TABLE konsumationsangebot (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     bigint NOT NULL,
    bezeichnung  varchar(255) NOT NULL,
    preis        numeric(38,2) NOT NULL,
    CONSTRAINT fk_konsumationsangebot_event FOREIGN KEY (event_id) REFERENCES event (id)
);

CREATE TABLE allgemeinausgabe (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      bigint NOT NULL,
    beschreibung  varchar(255) NOT NULL,
    herkunft      varchar(255),
    betrag        numeric(38,2) NOT NULL,
    CONSTRAINT fk_allgemeinausgabe_event FOREIGN KEY (event_id) REFERENCES event (id)
);

-- ---------------------------------------------------------------------------
-- Durchführung
-- ---------------------------------------------------------------------------

CREATE TABLE konsumation (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teilnahme_id            bigint NOT NULL,
    konsumationsangebot_id  bigint NOT NULL,
    anzahl                  integer NOT NULL,
    CONSTRAINT fk_konsumation_teilnahme           FOREIGN KEY (teilnahme_id)           REFERENCES teilnahme (id),
    CONSTRAINT fk_konsumation_konsumationsangebot FOREIGN KEY (konsumationsangebot_id) REFERENCES konsumationsangebot (id)
);

-- ---------------------------------------------------------------------------
-- Nachbearbeitung
-- ---------------------------------------------------------------------------

CREATE TABLE abrechnung (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teilnahme_id            bigint NOT NULL,
    anteil_allgemeinkosten  numeric(38,2) NOT NULL,
    total_konsumation       numeric(38,2) NOT NULL,
    total_betrag            numeric(38,2) NOT NULL,
    zustellungskanal        varchar(255) NOT NULL,
    zustellungs_datum       date,
    CONSTRAINT fk_abrechnung_teilnahme FOREIGN KEY (teilnahme_id) REFERENCES teilnahme (id),
    CONSTRAINT uk_abrechnung_teilnahme UNIQUE (teilnahme_id),
    CONSTRAINT abrechnung_zustellungskanal_check CHECK (zustellungskanal IN ('TWINT', 'EMAIL', 'PAPIER'))
);

CREATE TABLE zahlung (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    abrechnung_id  bigint NOT NULL,
    zahlungskanal  varchar(255) NOT NULL,
    datum          date NOT NULL,
    betrag         numeric(38,2) NOT NULL,
    CONSTRAINT fk_zahlung_abrechnung FOREIGN KEY (abrechnung_id) REFERENCES abrechnung (id),
    CONSTRAINT zahlung_zahlungskanal_check CHECK (zahlungskanal IN ('TWINT', 'UEBERWEISUNG', 'BAR'))
);

CREATE TABLE mahnung (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    abrechnung_id  bigint NOT NULL,
    datum          date NOT NULL,
    bemerkung      varchar(255),
    CONSTRAINT fk_mahnung_abrechnung FOREIGN KEY (abrechnung_id) REFERENCES abrechnung (id)
);

-- ---------------------------------------------------------------------------
-- Auth (AUTH-002)
-- ---------------------------------------------------------------------------

CREATE TABLE benutzer (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          varchar(255) NOT NULL,
    passwort_hash  varchar(255) NOT NULL,
    rolle          varchar(255) NOT NULL,
    partei_id      bigint,
    CONSTRAINT uk_benutzer_email  UNIQUE (email),
    CONSTRAINT fk_benutzer_partei FOREIGN KEY (partei_id) REFERENCES partei (id),
    CONSTRAINT benutzer_rolle_check CHECK (rolle IN ('ORGANISATOR', 'PARTEI'))
);
